# Generated by Django 5.2.17 on 2026-08-07 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_point', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alert', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('purchase', 'خرید'), ('production', 'تولید'), ('sale', 'فروش'), ('return_in', 'بازگشت به انبار'), ('adjustment', 'اصلاح موجودی'), ('scrap', 'ضایعات')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Signed: negative for sale/scrap, positive otherwise.')),
                ('balance_after', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, help_text='e.g. order number', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
