# Generated by Django 5.2.17 on 2026-08-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_seed_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='kavenegar_template_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='smslog',
            name='kavenegar_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='kavenegar_template_name',
            field=models.CharField(blank=True, help_text='نام الگوی Lookup در پنل کاوه\u200cنگار (نه شناسه عددی). خالی = ارسال متن معمولی با body.', max_length=100),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='kavenegar_token_field',
            field=models.CharField(blank=True, help_text='کدام کلید از context به\u200cعنوان %token% به کاوه\u200cنگار فرستاده شود، مثلاً code یا orderNumber.', max_length=50),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='body',
            field=models.TextField(blank=True, help_text='Use {placeholders} like {code}, {orderNumber}'),
        ),
    ]
