# Generated by Django 5.2.17 on 2026-08-08 00:19

import apps.content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(default='PDF', max_length=20)),
                ('file_url', models.CharField(max_length=500)),
                ('file_size_mb', models.DecimalField(decimal_places=1, max_digits=6)),
                ('page_count', models.PositiveIntegerField()),
                ('edition', models.CharField(max_length=50)),
                ('cover_image', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'catalog file',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='external_cover_url',
            field=models.CharField(blank=True, help_text='Static asset path, used until a real image is uploaded.', max_length=500),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='tracking_code',
            field=models.CharField(default=apps.content.models.generate_tracking_code, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.CreateModel(
            name='CatalogEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('page_count', models.PositiveIntegerField()),
                ('file_size_mb', models.DecimalField(decimal_places=1, max_digits=6)),
                ('file_url', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='content.catalogfile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CatalogSpread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreads', to='content.catalogfile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
