# Generated by Django 5.2.17 on 2026-08-23 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_external_image_url_and_more'),
        ('content', '0004_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='۱ تا ۶')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('link_url', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('image_mobile', models.ImageField(blank=True, help_text='اختیاری — نسخه افقی دسکتاپ روی موبایل معمولاً بد کراپ می\u200cشود', null=True, upload_to='homepage/')),
                ('image_alt', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('caption', models.CharField(blank=True, help_text='مونو، مثلاً "PLA · FDM · 0.2MM LAYER"', max_length=100)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'hero section',
            },
        ),
        migrations.CreateModel(
            name='HomeShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='۱ یا ۲')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('specs', models.JSONField(default=list, help_text='[{label, value}, ...] — mono-rendered on the frontend')),
                ('cta_label', models.CharField(default='جزئیات را ببینید', max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('theme', models.CharField(choices=[('light', 'روشن'), ('dark', 'تیره')], default='light', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
