# Generated by Django 5.2.17 on 2026-08-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cart_one_cart_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('ZARINPAL', 'زرین\u200cپال'), ('IDPAY', 'آیدی\u200cپی'), ('SNAPPPAY', 'اسنپ\u200cپی'), ('DIGIPAY', 'دیجی\u200cپی')], max_length=20),
        ),
    ]
