# Generated by Django 5.2.17 on 2026-08-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment_gateway_name_alter_payment_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
