# Generated by Django 5.2.17 on 2026-08-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='external_image_url',
            field=models.CharField(blank=True, help_text='Static asset path, used until a real image is uploaded.', max_length=500),
        ),
        migrations.AddField(
            model_name='productimage',
            name='external_url',
            field=models.CharField(blank=True, help_text='Static asset path, used until a real image is uploaded.', max_length=500),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
