# Generated by Django 5.2.17 on 2026-09-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_external_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='return_policy',
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_terms',
            field=models.TextField(blank=True, help_text='مثلاً "۶ ماه گارانتی تعویض در صورت نقص ساخت."'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
