# Generated by Django 5.2.17 on 2026-09-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_product_return_policy_product_warranty_terms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='layer_height_mm',
        ),
    ]
