import type { OrderStatus } from "@/types/order";

export const orderStatusLabel: Record<OrderStatus, string> = {
  pending: "در انتظار پرداخت",
  paid: "پرداخت‌شده",
  processing: "در حال آماده‌سازی",
  shipped: "ارسال شده",
  delivered: "تحویل شد",
  canceled: "لغو شد",
  returned: "مرجوع شده",
};

export const accountContent = {
  seo: { title: "حساب کاربری", description: "سفارش‌ها، آدرس‌ها و اطلاعات حساب کاربری شما در VYBE." },
  breadcrumbLabel: "حساب کاربری",
  logout: "خروج از حساب",
  tabs: {
    orders: "سفارش‌های من",
    detail: "جزئیات سفارش",
    addresses: "آدرس‌ها",
    favorites: "علاقه‌مندی‌ها",
    profile: "اطلاعات حساب",
  },
  orders: {
    heading: "سفارش‌های من",
    countTemplate: (n: number) => `${n} سفارش`,
    detailsCta: "جزئیات",
    loading: "در حال بارگذاری…",
    loadError: "دریافت سفارش‌ها ناموفق بود.",
    retry: "تلاش دوباره",
    empty: {
      heading: "هنوز سفارشی ثبت نکرده‌اید",
      body: "وقتی اولین سفارش را ثبت کنید، وضعیت و کد رهگیری‌اش همین‌جا می‌آید.",
      cta: "دیدن محصولات",
    },
  },
  detail: {
    back: "بازگشت",
    orderTitle: (number: string) => `سفارش ${number}`,
    statusHeading: "وضعیت سفارش",
    orderCreated: "ثبت سفارش",
    trackingLabel: "TRACKING",
    trackingPending: "هنوز صادر نشده",
    itemsHeading: "اقلام سفارش",
    paymentHeading: "پرداخت",
    subtotalLabel: "جمع کالاها",
    discountLabel: "تخفیف",
    shippingLabel: "ارسال",
    totalLabel: "مبلغ نهایی",
    gatewayLabel: "درگاه پرداخت",
    refIdLabel: "کد رهگیری تراکنش",
    paidAtLabel: "زمان تراکنش",
    noPayments: "هنوز پرداختی برای این سفارش ثبت نشده است.",
    addressHeading: "آدرس تحویل",
    invoiceButton: "دانلود فاکتور",
    invoiceUnavailable: "خروجی فاکتور در فاز بعدی فعال می‌شود.",
    cancelButton: "درخواست لغو",
    cancelUnavailable: "لغو سفارش از پنل کاربری در فاز بعدی فعال می‌شود.",
    loading: "در حال بارگذاری…",
    loadError: "دریافت جزئیات سفارش ناموفق بود.",
    retry: "تلاش دوباره",
    selectPrompt: (ordersTabLabel: string) => `یک سفارش را از تب «${ordersTabLabel}» انتخاب کنید.`,
  },
  addresses: {
    heading: "آدرس‌ها",
    countTemplate: (n: number) => `${n} آدرس ذخیره‌شده`,
    addNew: "+ آدرس جدید",
    defaultBadge: "پیش‌فرض",
    edit: "ویرایش",
    makeDefault: "پیش‌فرض کن",
    remove: "حذف",
    empty: "هیچ آدرسی ذخیره نشده است. اولین آدرس را در همین صفحه اضافه کنید.",
    form: {
      addHeading: "افزودن آدرس",
      editHeading: "ویرایش آدرس",
      titleLabel: "عنوان آدرس *",
      titlePlaceholder: "خانه، محل کار",
      nameLabel: "گیرنده *",
      namePlaceholder: "نام و نام خانوادگی",
      postalLabel: "کد پستی *",
      postalPlaceholder: "۱۰ رقم",
      phoneLabel: "موبایل *",
      phonePlaceholder: "09xxxxxxxxx",
      lineLabel: "نشانی کامل *",
      linePlaceholder: "خیابان، کوچه، پلاک، واحد",
      provinceLabel: "استان *",
      cityLabel: "شهر *",
      defaultLabel: "این آدرس پیش‌فرض باشد.",
      save: "ذخیره آدرس",
      saving: "در حال ذخیره…",
      cancel: "انصراف",
      formError: "چند فیلد کامل نیست. موارد مشخص‌شده را بررسی کنید.",
      saveError: "آدرس ذخیره نشد. دوباره تلاش کنید.",
    },
  },
  profile: {
    heading: "اطلاعات حساب",
    firstNameLabel: "نام",
    lastNameLabel: "نام خانوادگی",
    emailLabel: "ایمیل",
    phoneLabel: "شماره موبایل",
    phoneHint: "شماره موبایل شناسه ورود است و تغییر آن نیاز به تأیید پیامکی دارد.",
    save: "ذخیره تغییرات",
    saving: "در حال ذخیره…",
    saveSuccess: "تغییرات ذخیره شد.",
    saveError: "ذخیره تغییرات ناموفق بود.",
  },
};
