export const authContent = {
  seo: {
    title: "ورود و ثبت‌نام",
    description: "ورود یا ثبت‌نام در VYBE با شماره موبایل و کد یک‌بارمصرف — بدون رمز عبور.",
  },
  breadcrumbLabel: "ورود و ثبت‌نام",
  phoneStep: {
    kicker: "STEP 1 · MOBILE",
    heading: "ورود یا ثبت‌نام",
    subtitle: "شماره موبایل خود را وارد کنید. اگر حساب نداشته باشید، همین‌جا ساخته می‌شود.",
    phoneLabel: "شماره موبایل *",
    phonePlaceholder: "09xxxxxxxxx",
    rulesLabel: "شرایط استفاده و سیاست حریم خصوصی را می‌پذیرم. *",
    submit: "دریافت کد تأیید",
    submitting: "در حال ارسال کد…",
  },
  otpStep: {
    kicker: "STEP 2 · OTP",
    heading: "کد تأیید",
    subtitleBefore: "کد شش رقمی به",
    subtitleAfter: "پیامک شد.",
    changeNumber: "تغییر شماره",
    resendPrefix: "ارسال مجدد تا",
    resendAction: "ارسال مجدد کد",
    submit: "تأیید و ورود",
    submitting: "در حال بررسی…",
    incompleteError: "هر شش رقم کد را وارد کنید.",
  },
  profileStep: {
    kicker: "STEP 3 · NEW ACCOUNT",
    heading: "تکمیل ثبت‌نام",
    subtitle: "شماره تأیید شد. برای ساخت حساب فقط نام لازم است؛ بقیه را بعداً می‌توانید کامل کنید.",
    nameLabel: "نام و نام خانوادگی *",
    namePlaceholder: "مثلاً سارا محمدی",
    emailLabel: "ایمیل",
    emailPlaceholder: "name@example.com",
    emailHint: "برای رسید سفارش و پیگیری. اختیاری است.",
    submit: "ساخت حساب",
    submitting: "در حال ساخت حساب…",
  },
  done: {
    heading: "خوش آمدید",
    body: "حساب شما آماده است.",
    accountCta: "حساب کاربری",
    homeCta: "بازگشت به فروشگاه",
  },
  passwordNote: "ورود با رمز عبور نداریم. هر بار یک کد یک‌بارمصرف پیامک می‌شود؛ رمزی برای فراموش کردن وجود ندارد.",
  side: {
    imageCaption: "WORKSHOP DETAIL SHOT",
    items: [
      "پیگیری سفارش و کد رهگیری در یک صفحه",
      "آدرس‌های ذخیره‌شده برای خرید بعدی",
      "سابقه قطعه‌هایی که خریده‌اید، برای چاپ دوباره",
    ],
  },
};
