export const checkoutContent = {
  seo: { title: "تسویه حساب", description: "آدرس تحویل، روش ارسال و پرداخت سفارش شما در VYBE." },
  breadcrumbLabel: "تسویه حساب",
  heading: "تسویه حساب",
  steps: { address: "آدرس", shipping: "ارسال", payment: "پرداخت" },

  address: {
    kicker: "STEP 1 · ADDRESS",
    heading: "آدرس تحویل",
    loading: "در حال بارگذاری آدرس‌ها…",
    loadError: "دریافت آدرس‌ها ناموفق بود.",
    retry: "تلاش دوباره",
    empty: "هنوز آدرسی ثبت نکرده‌اید. اولین آدرس را همین‌جا اضافه کنید.",
    addNew: "+ افزودن آدرس جدید",
    cancelAddNew: "انصراف از افزودن آدرس",
    continueCta: "ادامه به روش ارسال",
    selectError: "یک آدرس را انتخاب کنید.",
    form: {
      titleLabel: "عنوان آدرس *",
      titlePlaceholder: "خانه، محل کار",
      nameLabel: "گیرنده *",
      namePlaceholder: "نام و نام خانوادگی",
      postalLabel: "کد پستی *",
      postalPlaceholder: "۱۰ رقم",
      phoneLabel: "موبایل گیرنده *",
      phonePlaceholder: "09xxxxxxxxx",
      lineLabel: "نشانی کامل *",
      linePlaceholder: "خیابان، کوچه، پلاک، واحد",
      provinceLabel: "استان *",
      cityLabel: "شهر *",
      defaultLabel: "این آدرس پیش‌فرض باشد.",
      save: "ذخیره و انتخاب",
      saving: "در حال ذخیره…",
      saveError: "آدرس ذخیره نشد. دوباره تلاش کنید.",
    },
  },

  shipping: {
    kicker: "STEP 2 · SHIPPING",
    heading: "روش ارسال",
    loading: "در حال بارگذاری روش‌های ارسال…",
    loadError: "دریافت روش‌های ارسال ناموفق بود.",
    retry: "تلاش دوباره",
    empty: "در حال حاضر روش ارسالی فعال نیست.",
    freeAboveTemplate: (amount: string) => `ارسال رایگان برای سفارش‌های بالای ${amount}`,
    continueCta: "ادامه به پرداخت",
    back: "بازگشت",
    selectError: "یک روش ارسال را انتخاب کنید.",
  },

  payment: {
    kicker: "STEP 3 · PAYMENT",
    heading: "روش پرداخت",
    loading: "در حال بارگذاری درگاه‌های پرداخت…",
    loadError: "دریافت درگاه‌های پرداخت ناموفق بود.",
    retry: "تلاش دوباره",
    unavailableHeading: "پرداخت آنلاین موقتاً در دسترس نیست",
    unavailableBody: "هیچ درگاه پرداختی در حال حاضر فعال نیست. لطفاً با پشتیبانی تماس بگیرید.",
    contactCta: "تماس با ما",
    selectGatewayLegend: "انتخاب درگاه *",
    selectError: "یک درگاه پرداخت انتخاب کنید.",
    couponLabel: "کد تخفیف",
    couponPlaceholder: "اختیاری",
    termsLabel: "شرایط خرید و سیاست مرجوعی را خوانده‌ام. *",
    termsError: "برای ادامه باید شرایط را بپذیرید.",
    back: "بازگشت",
    payCtaTemplate: (amount: string) => `پرداخت ${amount}`,
    redirecting: "در حال انتقال به درگاه پرداخت…",
    redirectingHint: "صفحه را نبندید.",
    genericError: "ثبت سفارش ناموفق بود. دوباره تلاش کنید.",
  },

  summary: {
    heading: "خلاصه سفارش",
    subtotalLabel: "جمع کالاها",
    shippingLabel: "ارسال",
    shippingPending: "بعد از انتخاب روش ارسال",
    payableLabel: "مبلغ قابل پرداخت",
    editCartLink: "ویرایش سبد",
  },

  loading: "در حال بارگذاری…",
  cartLoadError: "دریافت سبد خرید ناموفق بود.",
  emptyCart: {
    heading: "سبد خرید خالی است",
    body: "برای تسویه حساب، ابتدا چیزی به سبد خرید اضافه کنید.",
    cta: "دیدن محصولات",
  },

  callback: {
    seo: { title: "نتیجه پرداخت", description: "نتیجه پرداخت سفارش شما در VYBE." },
    successHeading: "سفارش ثبت شد",
    successBodyTemplate: (orderNumber: string) => `پرداخت سفارش ${orderNumber} با موفقیت انجام شد.`,
    failureHeading: "پرداخت ناموفق بود",
    failureBody: "تراکنش تکمیل نشد یا لغو شد. مبلغی کسر نشده است؛ اگر کسر شده تا ۷۲ ساعت برمی‌گردد. سبد و آدرس شما حفظ شده است.",
    trackOrderCta: "پیگیری سفارش",
    continueShoppingCta: "ادامه خرید",
    retryCta: "بازگشت به سبد خرید",
  },
} as const;
