export const productDetailContent = {
  reviewsAnchor: "دیدگاه‌ها",
  reviewsCountLabel: "۲۳ دیدگاه ثبت‌شده",
  ratingValue: 4.6,
  ratingCount: 23,
  priceNote: "قیمت نهایی؛ ارسال جداگانه محاسبه می‌شود.",
  colorLegend: "رنگ فیلامنت",
  addToCart: "افزودن به سبد",
  addingToCart: "در حال افزودن…",
  addedToCartToast: "به سبد اضافه شد.",
  addToCartErrorToast: "افزودن به سبد ناموفق بود.",
  viewCart: "مشاهده سبد",
  outOfStock: "ناموجود",
  saveToFavorites: "ذخیره در علاقه‌مندی‌ها",
  share: "SHARE",
  shipping: { label: "ارسال", value: "۲ تا ۴ روز کاری، تهران و شهرستان" },
  returns: { label: "مرجوعی", value: "۷ روز، بدون قید" },
  buildStatus: { label: "وضعیت ساخت", inStock: "IN STOCK · SHIPS FROM WORKSHOP", outOfStock: "OUT OF STOCK" },
  lowStockTemplate: (count: number, colorName: string) => `تنها ${count.toLocaleString("en-US")} عدد در رنگ ${colorName} باقی مانده است.`,
  whyThisShape: {
    heading: "چرا این شکل",
    highlights: [
      "پرینت‌شده به‌صورت یک‌تکه، بدون پیچ یا چسب",
      "سطح مات، اثر انگشت نمی‌گیرد",
      "بازرسی دستی قبل از ارسال",
    ],
  },
  specTable: {
    kicker: "TECHNICAL SPEC",
    labels: { sku: "کد مدل", dimensions: "ابعاد", weight: "وزن", material: "متریال", layerHeight: "ارتفاع لایه", category: "دسته‌بندی" },
    careNoteBefore: "PLA در آفتاب مستقیم داخل خودرو نرم می‌شود. جزئیات نگهداری در",
    careLinkLabel: "راهنمای نگهداری قطعات",
  },
  howItsMade: {
    kicker: "HOW IT IS MADE",
    heading: "خط لایه را پنهان نمی‌کنیم",
    body: "هر قطعه در کارگاه خودمان چاپ، پخ‌زنی و بازرسی می‌شود. رد ساخت روی سطح می‌ماند؛ این بخشی از شکل محصول است، نه نقص آن.",
    macroImageAlt: "MACRO · LAYER LINES 0.2 MM",
    linkLabel: "فرایند تولید",
  },
  reviews: {
    heading: "دیدگاه‌ها",
    ofLabel: "از ۲۳ دیدگاه",
    writeReview: "نوشتن دیدگاه",
    distribution: [
      { star: 5, count: 15, pct: 65 },
      { star: 4, count: 6, pct: 26 },
      { star: 3, count: 2, pct: 9 },
      { star: 2, count: 0, pct: 0 },
      { star: 1, count: 0, pct: 0 },
    ],
    items: [
      { name: "سارا م.", date: "1404/03/11", rating: 5, body: "اندازه‌اش دقیقاً همان چیزی است که در مشخصات نوشته." },
      { name: "امیر ک.", date: "1404/02/28", rating: 4, body: "کیفیت سطح خوب است ولی رنگ کمی روشن‌تر از عکس سایت به نظر می‌رسد." },
      { name: "نگار ر.", date: "1404/02/09", rating: 5, body: "دو ماه استفاده کردم، نه ترک خورد نه لق شد." },
    ],
    confirmedPurchase: "خرید تأییدشده",
  },
  related: {
    heading: "در همین دسته",
    viewAllTemplate: (categoryName: string) => `همه محصولات ${categoryName}`,
  },
} as const;
