# Generated by Django 5.2.17 on 2026-08-10 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_role', to='auth.group')),
            ],
            options={
                'ordering': ['group__name'],
                'permissions': [('sec_products_view', 'محصولات — view'), ('sec_products_create', 'محصولات — create'), ('sec_products_edit', 'محصولات — edit'), ('sec_products_delete', 'محصولات — delete'), ('sec_categories_view', 'دسته\u200cبندی\u200cها — view'), ('sec_categories_create', 'دسته\u200cبندی\u200cها — create'), ('sec_categories_edit', 'دسته\u200cبندی\u200cها — edit'), ('sec_categories_delete', 'دسته\u200cبندی\u200cها — delete'), ('sec_specs_view', 'مشخصات محصولات — view'), ('sec_specs_create', 'مشخصات محصولات — create'), ('sec_specs_edit', 'مشخصات محصولات — edit'), ('sec_specs_delete', 'مشخصات محصولات — delete'), ('sec_pricing_view', 'اصلاح قیمت — view'), ('sec_pricing_edit', 'اصلاح قیمت — edit'), ('sec_cost_price_view', 'قیمت تمام\u200cشده محصول — view'), ('sec_orders_view', 'سفارشات — view'), ('sec_orders_edit', 'سفارشات — edit'), ('sec_inventory_view', 'موجودی — view'), ('sec_inventory_edit', 'موجودی — edit'), ('sec_stock_ledger_view', 'کاردکس — view'), ('sec_stock_ledger_create', 'کاردکس — create'), ('sec_returns_view', 'مرجوعی\u200cها — view'), ('sec_returns_edit', 'مرجوعی\u200cها — edit'), ('sec_messages_view', 'پیام\u200cها — view'), ('sec_messages_edit', 'پیام\u200cها — edit'), ('sec_reviews_view', 'نظرات — view'), ('sec_reviews_edit', 'نظرات — edit'), ('sec_blog_view', 'بلاگ — view'), ('sec_blog_create', 'بلاگ — create'), ('sec_blog_edit', 'بلاگ — edit'), ('sec_blog_delete', 'بلاگ — delete'), ('sec_coupons_view', 'کدهای تخفیف — view'), ('sec_coupons_create', 'کدهای تخفیف — create'), ('sec_coupons_edit', 'کدهای تخفیف — edit'), ('sec_coupons_delete', 'کدهای تخفیف — delete'), ('sec_reports_view', 'گزارش\u200cهای فروش و سود — view'), ('sec_settings_view', 'تنظیمات سایت — view'), ('sec_settings_edit', 'تنظیمات سایت — edit'), ('sec_credentials_view', 'کلیدهای API — view'), ('sec_credentials_edit', 'کلیدهای API — edit'), ('sec_users_view', 'کاربران — view'), ('sec_users_create', 'کاربران — create'), ('sec_users_edit', 'کاربران — edit'), ('sec_roles_view', 'مدیریت نقش\u200cها و دسترسی — view'), ('sec_roles_edit', 'مدیریت نقش\u200cها و دسترسی — edit'), ('sec_activity_log_view', 'لاگ فعالیت — view'), ('sec_search_console_view', 'سرچ کنسول — view')],
            },
        ),
    ]
