# Generated by Django 5.2.17 on 2026-08-07 23:58

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('kavenegar', 'کاوه\u200cنگار'), ('zarinpal', 'زرین\u200cپال'), ('idpay', 'آیدی\u200cپی'), ('snapppay', 'اسنپ\u200cپی'), ('digipay', 'دیجی\u200cپی')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('credentials', encrypted_model_fields.fields.EncryptedTextField(help_text='JSON string, e.g. {"apiKey": "...", "merchantId": "..."}')),
                ('is_active', models.BooleanField(default=True, help_text='controls checkout-time visibility')),
                ('is_sandbox', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['service', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.PositiveIntegerField()),
                ('free_above', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_days', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'cost'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_display', models.CharField(blank=True, max_length=30)),
                ('phone_href', models.CharField(blank=True, help_text='e.g. "+982112345678" for tel:', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('business_hours', models.JSONField(default=list, help_text='[{day, time}, ...]')),
                ('instagram_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('pinterest_url', models.URLField(blank=True)),
                ('google_maps_embed', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('trust_badge_label', models.CharField(blank=True, max_length=100)),
                ('trust_badge_image', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('trust_badge_url', models.URLField(blank=True)),
                ('payment_gateway_label', models.CharField(blank=True, max_length=100)),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('default_og_image', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
