# Generated by Django 5.2.17 on 2026-08-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notify_owner_new_order',
            field=models.BooleanField(default=True, help_text='پیامک به کارفرما پس از پرداخت موفق هر سفارش (نه هنگام ثبت سفارش pending)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='owner_notification_phone',
            field=models.CharField(blank=True, help_text='یک یا چند شماره، جدا با کاما — مثلاً 09120000000,09121111111', max_length=200),
        ),
    ]
