# Generated by Django 5.2.17 on 2026-08-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_sitesettings_notify_owner_new_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredential',
            name='description',
            field=models.CharField(blank=True, help_text='مثلاً «پرداخت اعتباری» برای اسنپ\u200cپی', max_length=150),
        ),
        migrations.AddField(
            model_name='apicredential',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/gateways/'),
        ),
    ]
