# Generated by Django 5.2.17 on 2026-08-08 16:21

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_apicredential_description_apicredential_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicredential',
            name='credentials',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='JSON string, e.g. {"apiKey": "...", "merchantId": "..."}'),
        ),
    ]
