# Generated by Django 5.2.17 on 2026-08-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_apicredential_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='business_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='economic_code',
            field=models.CharField(blank=True, help_text='کد اقتصادی', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='national_id',
            field=models.CharField(blank=True, help_text='شناسه ملی', max_length=30),
        ),
    ]
