# Generated by Django 5.2.17 on 2026-08-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_sitesettings_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='payment_gateway_image',
            field=models.ImageField(blank=True, help_text='لوگوی درگاه پرداخت که در فوتر کنار «نماد اعتماد» نشان داده می\u200cشود. فرمت PNG (پس\u200cزمینه شفاف) یا SVG، حداقل ۱۲۰×۱۲۰ پیکسل، حجم زیر ۲۰۰ کیلوبایت.', null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_badge_image_url',
            field=models.URLField(blank=True, help_text='برای eNamad: کل کد نماد را در فیلد «لینک نماد» پیست کن، این فیلد خودکار پر می\u200cشود.', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_og_image',
            field=models.ImageField(blank=True, help_text='فعلاً در سایت زنده استفاده نمی\u200cشود — تصویر پیش\u200cفرض اشتراک\u200cگذاری از فایل ثابت خوانده می\u200cشود. فرمت JPG یا PNG، ۱۲۰۰×۶۳۰ پیکسل.', null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='فعلاً در سایت زنده استفاده نمی\u200cشود — فاوآیکون فعلی از فایل ثابت index.html خوانده می\u200cشود. فرمت ICO یا PNG ۳۲×۳۲ یا ۶۴×۶۴ پیکسل.', null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='لینک کامل، مثلاً https://instagram.com/vybeshop — خالی بگذار تا در فوتر/تماس با ما نمایش داده نشود.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='لینک کامل — خالی بگذار تا نمایش داده نشود.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='فعلاً در سایت زنده استفاده نمی\u200cشود.', null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_light',
            field=models.ImageField(blank=True, help_text='فعلاً در سایت زنده استفاده نمی\u200cشود — سایت از یک لوگوی طراحی\u200cشده ثابت استفاده می\u200cکند، نه از این آپلود.', null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='pinterest_url',
            field=models.URLField(blank=True, help_text='لینک کامل — خالی بگذار تا نمایش داده نشود.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True, help_text='لینک کامل — خالی بگذار تا نمایش داده نشود.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='trust_badge_image',
            field=models.ImageField(blank=True, help_text='فقط اگر نماد اعتمادت eNamad نیست و عکس ثابت داری از اینجا آپلود کن. فرمت PNG (پس\u200cزمینه شفاف) یا SVG، حداقل ۱۲۰×۱۲۰ پیکسل، حجم زیر ۲۰۰ کیلوبایت. برای eNamad به\u200cجایش «تصویر نماد (لینک eNamad)» را پر کن.', null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='trust_badge_url',
            field=models.URLField(blank=True, help_text='لینک نماد. برای eNamad می\u200cتوانی کل کد <a>...</a> نماد را همینجا پیست کنی -- لینک و عکس هردو خودکار استخراج می\u200cشوند.', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='لینک کامل (مثلاً https://wa.me/98912...) — خالی بگذار تا نمایش داده نشود.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='لینک کامل — خالی بگذار تا نمایش داده نشود.'),
        ),
    ]
